before:
  hooks:
    - go mod tidy -v
builds:
  - id: nezha-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm
      - arm64
      - 386
      - amd64
      - mips
    gomips:
      - softfloat
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    main: ./cmd/agent
    binary: nezha-agent
    # 为路由器、开发板缩小二进制体积
    hooks:
      post:
        - upx --best "{{.Path}}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{.ProjectName}}"
archives:
  - name_template: "nezha-agent_{{ .Os }}_{{ .Arch }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
